### ISSUE TITLE
Server fails when CORS enabled and no WHITELIST is present

### ISSUE THREAD

**Issue by allanbowe** [sasjs/server#125]
To reproduce, deploy an app with `CORS=enable` and `WHITELIST=`

Expected - the app would still work when the domain is the same

Nice to have - if WHITELIST is empty then ALL domains are accessible (it would be fine to throw an ERROR or WARNING in the console for this)

**Comment by saadjutt01** [comment]
Cannot allow all (*) for origin with `credentials: true` which is required.

Ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials

Throwing error for no WHITELIST provided Or invalid URL is present ( if explicitly set CORS=enable)
<img width="387" alt="image" src="https://user-images.githubusercontent.com/8914650/182723300-229a34d9-70dd-4d66-b3b9-fd7e8476acff.png">
<img width="442" alt="image" src="https://user-images.githubusercontent.com/8914650/182723476-988d893a-aa78-427d-aeac-f2da18ba8e0f.png">
