### ISSUE TITLE
stp/execute does not handle colon in filename in header

### ISSUE THREAD

**Issue by allanbowe** [sasjs/server#143]
Example header:

```
[allbow@sas 20220424001949-96988-1650759589476]$ vi stpsrv_header.txt 

Content-type: application/zip
Content-disposition: attachment; filename="2022-04-24T00:23:36.993Z-compare-releases.zip"
```

The downloaded file has the filename:  `2022-04-24T00`

**Comment by saadjutt01** [comment]
Not possible to have ':' in filename over HTTP request

Ref: https://stackoverflow.com/questions/48755029/how-to-get-colons-in-filenames-using-content-disposition

**Comment by allanbowe** [comment]
Indeed - seems it's not compatible in all operating systems to have a `:` in a filename.  My bad!
