### ISSUE TITLE
set logging levels

### ISSUE THREAD

**Issue by allanbowe** [sasjs/server#145]
It should be possible to set the log level in the `.env` file, eg:

- COMMON  https://www.npmjs.com/package/morgan#common
- DEV https://www.npmjs.com/package/morgan#dev
- SHORT https://www.npmjs.com/package/morgan#short
- TINY https://www.npmjs.com/package/morgan#tiny

To change in code, https://github.com/sasjs/server/blob/main/api/src/app.ts#L38

the default should be:

`LOGFORMAT_MORGAN=COMMON`

**Comment by saadjutt01** [comment]
Using `LOG_FORMAT_MORGAN` instead of `LOGFORMAT_MORGAN`
