### ISSUE TITLE
Ability to create arbitrary content from a post request on a stored program

### ISSUE THREAD

**Issue by philipmason** [sasjs/server#257]
It would be really useful to be able to do things like stream graphics from a stored program, so I could then display that in my web application. So creating any kind of output, without a JSON log attached, would be great.

**Comment by allanbowe** [comment]
Thanks Phil - we've implemented direct output in POST requests now.  If the _DEBUG parameter is set, then the _webout content will be divided from the log using a UUID.

The SASjs adapter will handle this automatically.

**Comment by philipmason** [comment]
Thanks for doing this so quickly. It will be very helpful.
