### ISSUE TITLE
lengths of username/password

### ISSUE THREAD

**Issue by allanbowe** [sasjs/server#61]
currently we enforce a minimum length of 6 for both username / password.  this is too long for a username, and too short for a password.

We should enable the following:

* Minimum 3 for username
* Minimum 10 for password

There should probably be a max also?

Perhaps the Logon screen can display the rules.. ?

**Comment by saadjutt01** [comment]
yes, we have min and max rules, defined [here](https://github.com/sasjs/server/blob/232a73fd172ebd7d3f77a6b91538936ea5cbe457/api/src/utils/validation.ts#L4)
