### ISSUE TITLE
Change LOG response format

### ISSUE THREAD

**Issue by allanbowe** [sasjs/server#68]
Currently, the LOG is returned as a single encoded string.

This can cause memory problems when we have very large logs.  It is also problematic to parse within certain instances of SAS.

Instead, we should send the log in an array (ie, line by line).

This affects the following endpoints:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/4420615/154699752-de473e94-a904-440e-ad4d-9d413c9c536d.png">

There is likely to also be an impact on the adapter / cli, which ingests the log int the request history.

example format:
```
{
  log:{
    "1":"reallyh long ",
    "2":" log|",
    "3":"sasoasdfasdfasdfasdf"
  }
}

```

**Comment by saadjutt01** [comment]
new format:
```
{
  log: [ 
    { "1": "line 1 of log content" },
    { "2": "line 2 of log content" },
    { "3": "line 3 of log content" },
    { "4": "line 4 of log content" },
  ]
}
```
